// <auto-generated />
using System;
using MasterSTI.Mock.Issuer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterSTI.Mock.Issuer.Migrations
{
    [DbContext(typeof(IssuerDbContext))]
    [Migration("20260522184828_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterSTI.Mock.Issuer.Data.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Identities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            BirthDate = "1985-03-04",
                            Email = "toma.iliescu@verasign.demo",
                            FamilyName = "Iliescu",
                            GivenName = "Toma"
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-0000-0000-0000-000000000002"),
                            BirthDate = "1992-07-19",
                            Email = "thea.popescu@verasign.demo",
                            FamilyName = "Popescu",
                            GivenName = "Thea"
                        });
                });

            modelBuilder.Entity("MasterSTI.Mock.Issuer.Data.IssuedCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CnfJwkThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("IssuedCredentials");
                });

            modelBuilder.Entity("MasterSTI.Mock.Issuer.Data.IssuedCredential", b =>
                {
                    b.HasOne("MasterSTI.Mock.Issuer.Data.Identity", "Identity")
                        .WithMany("IssuedCredentials")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("MasterSTI.Mock.Issuer.Data.Identity", b =>
                {
                    b.Navigation("IssuedCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
