// <auto-generated />
using System;
using MasterSTI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterSTI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423000000_DropSignatureValueAddIndexes")]
    partial class DropSignatureValueAddIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterSTI.Api.Data.Document", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("ContentType").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                    b.Property<string>("Sha256Hash").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<string>("StoragePath").IsRequired().HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                    b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("UploadedAt");
                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MasterSTI.Api.Data.SignedDocument", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("OriginalDocumentId").HasColumnType("uniqueidentifier");
                    b.Property<string>("PadesLevel").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<DateTime>("SignedAt").HasColumnType("datetime2");
                    b.Property<Guid>("SigningRequestId").HasColumnType("uniqueidentifier");
                    b.Property<string>("StoragePath").IsRequired().HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                    b.Property<string>("TimestampToken").HasColumnType("nvarchar(max)");
                    b.Property<string>("ValidationReport").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("OriginalDocumentId");
                    b.HasIndex("SigningRequestId");
                    b.ToTable("SignedDocuments");
                });

            modelBuilder.Entity("MasterSTI.Api.Data.SigningRequest", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("CredentialId").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("DocumentHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<Guid>("DocumentId").HasColumnType("uniqueidentifier");
                    b.Property<string>("EudiwSubject").HasMaxLength(512).HasColumnType("nvarchar(512)");
                    b.Property<string>("PreparedStoragePath").HasMaxLength(1024).HasColumnType("nvarchar(1024)");
                    b.Property<string>("RequestedBy").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("SignatureLevel").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("DocumentId");
                    b.ToTable("SigningRequests");
                });

            modelBuilder.Entity("MasterSTI.Api.Data.SignedDocument", b =>
                {
                    b.HasOne("MasterSTI.Api.Data.Document", "OriginalDocument").WithMany().HasForeignKey("OriginalDocumentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MasterSTI.Api.Data.SigningRequest", "SigningRequest").WithMany().HasForeignKey("SigningRequestId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("OriginalDocument");
                    b.Navigation("SigningRequest");
                });

            modelBuilder.Entity("MasterSTI.Api.Data.SigningRequest", b =>
                {
                    b.HasOne("MasterSTI.Api.Data.Document", "Document").WithMany().HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Document");
                });
#pragma warning restore 612, 618
        }
    }
}
